galaxy_info:
  author: Yevhenii Rosliakov
  description: Join worker nodes to an existing Kubernetes cluster
  company: N/A

  license: MIT

  min_ansible_version: "2.1"

  galaxy_tags: []

dependencies: []
